version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chirpdb
      CHIRP_DBSCHEMA: chirp
      CHIRP_PUBLIC_DBSCHEMA: chirp_public
      CHIRP_DBUSER: admin
      CHIRP_USER_DBPASS: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./webserver/initdb.d/db.sh:/docker-entrypoint-initdb.d/db.sh:ro

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/chirpdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres-data:
    driver: local