#!/bin/sh
set -e

# Create table if not exists
psql --username "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'" | grep -q 1 || \
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE DATABASE $POSTGRES_DB WITH ENCODING 'UTF8';"

# Create user and grant access
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE USER $CHIRP_DBUSER WITH ENCRYPTED PASSWORD '$CHIRP_USER_DBPASS';"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $CHIRP_DBUSER;"
psql -v ON_ERROR_STOP=1 --username "$CHIRP_DBUSER" -c "CREATE SCHEMA $CHIRP_DBSCHEMA" $POSTGRES_DB;

psql -v ON_ERROR_STOP=1 --username "$CHIRP_DBUSER" -c "CREATE SCHEMA $CHIRP_PUBLIC_DBSCHEMA AUTHORIZATION $CHIRP_DBUSER" -d $POSTGRES_DB;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "GRANT ALL PRIVILEGES ON SCHEMA $CHIRP_PUBLIC_DBSCHEMA TO $CHIRP_DBUSER" -d $POSTGRES_DB;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "GRANT ALL ON ALL TABLES IN SCHEMA $CHIRP_PUBLIC_DBSCHEMA TO $CHIRP_DBUSER" -d $POSTGRES_DB;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "GRANT ALL ON ALL SEQUENCES IN SCHEMA $CHIRP_PUBLIC_DBSCHEMA TO $CHIRP_DBUSER" -d $POSTGRES_DB;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "GRANT ALL ON ALL FUNCTIONS IN SCHEMA $CHIRP_PUBLIC_DBSCHEMA TO $CHIRP_DBUSER" -d $POSTGRES_DB;